server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /book-system

spring:
  datasource:
    name : book
    url : jdbc:mysql://3.0.89.164:3306/book?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username : ENC(!..*)
    password: ENC(NOPQRS)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

jasypt:
  encryptor:
    password: 123
    bean: desencrypt
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

